<?php

class WordpressPage_Node extends Folder_Node {
   var $struct = array(
                       "node_type" => "WordpressPage_Node",
                       "title"     => array(
                                            "prop_type" => "callback",
                                            "name"    => "set_title"),
                       "page_id"   => array(
                                            "prop_type" => "callback",
                                            "name"    => "set_page_id"),
                       "import_nodes"     => array(
                                            "prop_type" => "callback",
                                            "name" => "import_nodes"
                                           )
                       );

   var $allowed_children_types = array ();

   static function insert_id ($id = NULL)
   {
      static $insert_id;

      if (!isset($insert_id) && $id != NULL) {
         $insert_id = $id;
      }

      return $insert_id;
   }

   function set_page_id ($name, $value)
   {
      if ($this->new) {
         $value = self::insert_id();
         $this->$name->set_value($value, $this->new);
      }

      $p = new Tag('p');
      if ($value) {
         $p->AddElement($value);
      } else {
         $p->AddElement('Page Id is autogenerated upon creation!');
      }

      return $p;
   }


   function set_title ($name, $value)
   {
      if ($this->id) {
         if ($this->new) {
            $page_id = self::insert_id();
         } else {
            $page_id = $this->page_id->value;
         }
      }

      $inputElement = new Tag('input', array('type'=>'text', 'name'=>'struct['.$name.']', 'value'=>$value));

      return $inputElement;

   }

   function import_nodes ($name, $value)
   {
      if ($this->id) {
         $div = new Tag('div');
         $childrenIds = array();

         if ($this->new) {
            $page_id = self::insert_id();
         } else {
            $page_id = $this->page_id->value;
         }

         $importedNodesElement = new Tag('select', array('name'=>'nodes_to_detach[]', 'multiple'=>'multiple', 'size'=>'10'));
         foreach ($this->get_array_of_children() as $child) {
            $option = new Tag('option', array('value'=>$child->id));
            $option->AddElement($child->title->value);
            $importedNodesElement->AddElement($option);
            $childrenIds[] = $child->id;
         }

         $div = new Tag('div');
         $selectElement = new Tag('select', array('name'=>'nodes_to_attach[]', 'multiple'=>'multiple', 'size'=>'10'));
         $rootNode = new Node(0);
         $rootNode->RecursiveOptionElement(array(), $childrenIds, $selectElement, 0, 
                                           array('Thread_Node', 
                                                 'Vote_Node', 
                                                 'WordpressPageSystem_Node', 
                                                 'DeleteSystem_Node'));
         $attachButton = new Tag('input', array('type'=>'submit', 'name'=>'action', 'value'=>'Attach'));
         $detachButton = new Tag('input', array('type'=>'submit', 'name'=>'action', 'value'=>'Detach'));
         $div->AddElement($selectElement);
         $div->AddElement($attachButton);
         $div->AddElement($detachButton);
         $div->AddElement($importedNodesElement);
         return $div;
      } else {
         $p = new Tag('p');
         $p->AddElement('Create Page before importing nodes');
         return $p;
      }
   }

   function doAttach ($container)
   {
      $nodesToAttach = SiG_Session::Instance()->Request('nodes_to_attach', NULL);
      if ($nodesToAttach) {
         foreach ($nodesToAttach as $nodeId) {
            $node = Node::new_instance($nodeId);
            $node->new = TRUE; //$this->new;
            $node->AttachTo($this->id);
         }
      }

      $this->doEdit($container);
   }

   function doDetach ($container)
   {
      $nodesToDetach = SiG_Session::Instance()->Request('nodes_to_detach', NULL);
      if ($nodesToDetach) {
         foreach ($nodesToDetach as $nodeId) {
            $node = Node::new_instance($nodeId);
            $node->new = TRUE; //$this->new;
            $node->DetachFrom($this->id);
         }
      }

      $this->doEdit($container);
   }

   function SetOrderBy ($parentId, $orderBy)
   {
      parent::SetOrderBy($parentId, $orderBy);
      $query = sprintf("UPDATE `wp_posts` SET menu_order='%d' WHERE ID='%d'",
                          mysqli_real_escape_string($orderBy),
                          mysqli_real_escape_string($this->page_id->value));
      $results = new Query($query);
   }

   function DefaultHtmlData ($container, $parentNode = NULL, $activeNode = NULL)
   {
      foreach ($this->get_array_of_children() as $child) {
         if ($activeNode->IsAncestor($child->id)) {
            $activeNode->ActiveHtmlData($container, $child);
         } else {
            $child->DefaultHtmlData($container, $this, $activeNode);
         }
      }
   }
}

?>
